### ISSUE TITLE
Attempting to watch missing directory: node_modules/progressbar.js

### ISSUE THREAD

**Issue by shumlvi** [null-null-null/ember-progress-bar#1]
```
Build error
Error: Attempting to watch missing directory: node_modules/progressbar.js
```

This error is caused by [this code](https://github.com/null-null-null/ember-progress-bar/blob/master/index.js#L18):

``` javascript
return new Funnel('node_modules/progressbar.js', {
    destDir: 'progressbar.js'
});
```

Installing `progressbar.js` in my own project solved this problem for now, but I consider this should be fixed in the addon.

**Comment by briarsweetbriar** [comment]
Thanks for catching that! The issue should be resolved by https://github.com/null-null-null/ember-progress-bar/commit/425b3507c392765947c16ff05a805f07f6657685. If you upgrade to v0.0.4, you'll see it working.
