### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by r22cky** [null-null-null/ember-progress-bar#3]
Hi! I just installed the addon on my ember prject and i got a deprecation warning. May be it was fix? I just wanted to let you know, here is the warning when lauching ember server:

```DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/devlecollectionist/Code/lecollectionist/customer-advising-dashboard/node_modules/ember-cli/lib/models/addon.js:1006:27)```

Thank you in advance! :)

**Comment by briarsweetbriar** [comment]
I don't believe this is being caused by `ember-progress-bar` itself, as it's not calling `init`. If you try removing `ember-progress-bar` from your code, do you still get this deprecation?

**Comment by r22cky** [comment]
Hey! Sorry for late answer :wink:

Yes I am sure it is due to ember-progress-bar, when i remove it and relaunch the ember server the deprecation warning disappear.

**Comment by briarsweetbriar** [comment]
Would it be possible for you to send me a link to the source code for your project? Or short of that, to copy in the template and controller/component that's using `ember-progress-bar`?

**Comment by r22cky** [comment]
Hey! The project is too big. We will try to make a little project out of it with the addon as soon as tomorrow and we will let you know.

**Comment by briarsweetbriar** [comment]
That would really help. Thanks, @r22cky!

**Comment by r22cky** [comment]
Ok @null-null-null I'm absolutely sorry, it was a mistake from me! Sorry for the trouble! I was thinking about ember-progress. 

Best regards,

**Comment by briarsweetbriar** [comment]
Glad to hear it's resolved!
